"""Model Registry tools for TransformerLens.

This package provides tools for discovering and documenting HuggingFace models
that are compatible with TransformerLens.

Main modules:
    - api: Public API for programmatic access to model registry data
    - schemas: Data classes for model entries, architecture gaps, etc.
    - verification: Verification tracking for model compatibility
    - exceptions: Custom exceptions for the model registry

Example usage:
    >>> from transformer_lens.tools.model_registry import api  # doctest: +SKIP
    >>> api.is_model_supported("openai-community/gpt2")  # doctest: +SKIP
    True
    >>> models = api.get_architecture_models("GPT2LMHeadModel")  # doctest: +SKIP
"""

from .exceptions import (
    ArchitectureNotSupportedError,
    DataNotLoadedError,
    DataValidationError,
    ModelNotFoundError,
    ModelRegistryError,
)
from .schemas import (
    ArchitectureAnalysis,
    ArchitectureGap,
    ArchitectureGapsReport,
    ArchitectureStats,
    ModelEntry,
    ModelMetadata,
    ScanInfo,
    SupportedModelsReport,
)
from .verification import VerificationHistory, VerificationRecord

# Canonical set of HuggingFace architecture class names supported by TransformerBridge.
# These must match the exact strings found in HF model config.architectures[]
# and correspond to adapters registered in architecture_adapter_factory.py.
#
# Internal-only architectures (NanoGPT, MinGPT, NeelSoluOld, GPT2LMHeadCustomModel,
# TransformerLensNative) are excluded since they never appear on HuggingFace Hub.
# Factory-internal alias casings (Gemma1, Neo, NeoX) are also excluded since they
# route to canonical adapters but HF reports the canonical names (Gemma, GPTNeo,
# GPTNeoX) in config.architectures instead.
HF_SUPPORTED_ARCHITECTURES: set[str] = {
    "AfmoeForCausalLM",
    "ApertusForCausalLM",
    "ArceeForCausalLM",
    "BaiChuanForCausalLM",
    "BaichuanForCausalLM",
    "BambaForCausalLM",
    "BartForConditionalGeneration",
    "BD3LM",
    "DreamModel",
    "Emu3ForConditionalGeneration",
    "AudioFlamingo3ForConditionalGeneration",
    "FlexOlmoForCausalLM",
    "GiddForDiffusionLM",
    "HyenaDNAForCausalLM",
    "LLaDA2MoeModelLM",
    "Jais2ForCausalLM",
    "JetMoeForCausalLM",
    "JetMoEForCausalLM",
    "LagunaForCausalLM",
    "Ministral3ForCausalLM",
    "VaultGemmaForCausalLM",
    "YoutuForCausalLM",
    "ModernBertDecoderForCausalLM",
    "MusicFlamingoForConditionalGeneration",
    "NanoChatForCausalLM",
    "RwkvForCausalLM",
    "SwitchTransformersForConditionalGeneration",
    "BertForMaskedLM",
    "BertLMHeadModel",
    "BitNetForCausalLM",
    "BlenderbotForConditionalGeneration",
    "BloomForCausalLM",
    "BloomModel",
    "CodeGenForCausalLM",
    "Cohere2ForCausalLM",
    "CohereForCausalLM",
    "DeepseekV2ForCausalLM",
    "DeepseekV3ForCausalLM",
    "Ernie4_5ForCausalLM",
    "Ernie4_5_MoeForCausalLM",
    "ExaoneForCausalLM",
    "Exaone4ForCausalLM",
    "DeepseekV4ForCausalLM",
    "FalconForCausalLM",
    "FalconH1ForCausalLM",
    "FalconMambaForCausalLM",
    "Florence2ForConditionalGeneration",
    "GemmaForCausalLM",
    "Gemma2ForCausalLM",
    "Gemma3ForCausalLM",
    "Gemma3ForConditionalGeneration",
    "Gemma3nForConditionalGeneration",
    "Gemma4ForConditionalGeneration",
    "Gemma4UnifiedForConditionalGeneration",
    "Gemma4ForCausalLM",
    "GlmForCausalLM",
    "Glm4ForCausalLM",
    "Glm4vForConditionalGeneration",
    "GlmAsrForConditionalGeneration",
    "Glm4MoeForCausalLM",
    "Glm4MoeLiteForCausalLM",
    "GlmMoeDsaForCausalLM",
    "GraniteForCausalLM",
    "GraniteMoeForCausalLM",
    "GraniteMoeHybridForCausalLM",
    "GPT2LMHeadModel",
    "GPTBigCodeForCausalLM",
    "GptOssForCausalLM",
    "GPTJForCausalLM",
    "GPTNeoForCausalLM",
    "OpenAIGPTLMHeadModel",
    "OpenELMForCausalLM",
    "GPTNeoXForCausalLM",
    "HubertForCTC",
    "HubertModel",
    "HrmTextForCausalLM",
    "HunYuanDenseV1ForCausalLM",
    "Idefics3ForConditionalGeneration",
    "InternLM2ForCausalLM",
    "LEDForConditionalGeneration",
    "LLaDAModelLM",
    "LlamaForCausalLM",
    "Llama4ForCausalLM",
    "Llama4ForConditionalGeneration",
    "LlavaForConditionalGeneration",
    "LlavaNextForConditionalGeneration",
    "LlavaOnevisionForConditionalGeneration",
    "Lfm2ForCausalLM",
    "Lfm2MoeForCausalLM",
    "LongT5ForConditionalGeneration",
    "M2M100ForConditionalGeneration",
    "MambaForCausalLM",
    "Mamba2ForCausalLM",
    "MarianMTModel",
    "MBartForConditionalGeneration",
    "MiniMaxM2ForCausalLM",
    "NemotronForCausalLM",
    "NemotronHForCausalLM",
    "MPTForCausalLM",
    "MptForCausalLM",
    "MistralForCausalLM",
    "Mistral3ForConditionalGeneration",
    "MixtralForCausalLM",
    "Olmo2ForCausalLM",
    "Olmo3ForCausalLM",
    "OlmoForCausalLM",
    "OlmoeForCausalLM",
    "OlmoHybridForCausalLM",
    "OPTForCausalLM",
    "PegasusForConditionalGeneration",
    "OuroForCausalLM",
    "PhiForCausalLM",
    "Phi3ForCausalLM",
    "PhiMoEForCausalLM",
    "QwenForCausalLM",
    "Qwen2ForCausalLM",
    "Qwen2_5_VLForConditionalGeneration",
    "Qwen3VLForConditionalGeneration",
    "Qwen3VLMoeForConditionalGeneration",
    "Qwen2AudioForConditionalGeneration",
    "Qwen2MoeForCausalLM",
    "Qwen3ForCausalLM",
    "Qwen3MoeForCausalLM",
    "Qwen3NextForCausalLM",
    "Qwen3_5ForCausalLM",
    "Qwen3_5ForConditionalGeneration",
    "Qwen3_5MoeForCausalLM",
    "Qwen3_5MoeForConditionalGeneration",
    "RecurrentGemmaForCausalLM",
    "SeedOssForCausalLM",
    "RWKV7ForCausalLM",
    "SmolLM3ForCausalLM",
    "StableLmForCausalLM",
    "Starcoder2ForCausalLM",
    "T5ForConditionalGeneration",
    "T5WithLMHeadModel",
    "MT5ForConditionalGeneration",
    "T5GemmaForConditionalGeneration",
    "T5Gemma2ForConditionalGeneration",
    "XGLMForCausalLM",
    "Zamba2ForCausalLM",
}

# Foundation-trained orgs per architecture. Source of truth for the scraper's
# download-threshold bypass and the docs table's "Canonical only" toggle.
CANONICAL_AUTHORS_BY_ARCH: dict[str, list[str]] = {
    "AfmoeForCausalLM": ["arcee-ai"],
    "ApertusForCausalLM": ["swiss-ai"],
    "ArceeForCausalLM": ["arcee-ai"],
    "BaiChuanForCausalLM": ["baichuan-inc"],
    "BaichuanForCausalLM": ["baichuan-inc"],
    "BambaForCausalLM": ["ibm-ai-platform"],
    "BartForConditionalGeneration": ["facebook"],
    "BD3LM": ["kuleshov-group"],
    "DreamModel": ["Dream-org", "apple"],
    "Emu3ForConditionalGeneration": ["BAAI"],
    "AudioFlamingo3ForConditionalGeneration": ["nvidia"],
    "FlexOlmoForCausalLM": ["allenai"],
    "GiddForDiffusionLM": ["dvruette"],
    "HyenaDNAForCausalLM": ["LongSafari"],
    "LLaDA2MoeModelLM": ["inclusionAI"],
    "Jais2ForCausalLM": ["inceptionai"],
    "JetMoeForCausalLM": ["jetmoe"],
    "JetMoEForCausalLM": ["jetmoe"],
    "LagunaForCausalLM": ["poolside"],
    "Ministral3ForCausalLM": ["mistralai"],
    "VaultGemmaForCausalLM": ["google"],
    "YoutuForCausalLM": ["tencent"],
    "ModernBertDecoderForCausalLM": ["jhu-clsp"],
    "MusicFlamingoForConditionalGeneration": ["nvidia"],
    "NanoChatForCausalLM": ["nanochat-students", "karpathy"],
    "RwkvForCausalLM": ["RWKV"],
    "SwitchTransformersForConditionalGeneration": ["google"],
    "BertForMaskedLM": ["google-bert"],
    "BertLMHeadModel": ["google-bert"],
    "BitNetForCausalLM": ["microsoft"],
    "BlenderbotForConditionalGeneration": ["facebook"],
    "BloomForCausalLM": ["bigscience"],
    "BloomModel": ["bigscience", "TurkuNLP"],
    "CodeGenForCausalLM": ["Salesforce"],
    "Cohere2ForCausalLM": ["CohereLabs"],
    "CohereForCausalLM": ["CohereLabs"],
    "DeepseekV2ForCausalLM": ["deepseek-ai"],
    "DeepseekV3ForCausalLM": ["deepseek-ai"],
    "Ernie4_5ForCausalLM": ["baidu"],
    "Ernie4_5_MoeForCausalLM": ["baidu"],
    "ExaoneForCausalLM": ["LGAI-EXAONE"],
    "Exaone4ForCausalLM": ["LGAI-EXAONE"],
    "DeepseekV4ForCausalLM": ["deepseek-ai"],
    "FalconForCausalLM": ["tiiuae"],
    "FalconH1ForCausalLM": ["tiiuae"],
    "FalconMambaForCausalLM": ["tiiuae"],
    "Florence2ForConditionalGeneration": ["florence-community", "microsoft"],
    "Gemma2ForCausalLM": ["google"],
    "Gemma3ForCausalLM": ["google"],
    "Gemma3ForConditionalGeneration": ["google"],
    "Gemma3nForConditionalGeneration": ["google"],
    "Gemma4ForConditionalGeneration": ["google"],
    "Gemma4UnifiedForConditionalGeneration": ["google"],
    "Gemma4ForCausalLM": ["google"],
    "GemmaForCausalLM": ["google"],
    "GlmForCausalLM": ["zai-org"],
    "Glm4ForCausalLM": ["zai-org", "THUDM"],
    "Glm4vForConditionalGeneration": ["zai-org", "THUDM"],
    "GlmAsrForConditionalGeneration": ["zai-org"],
    "Glm4MoeForCausalLM": ["zai-org"],
    "Glm4MoeLiteForCausalLM": ["zai-org"],
    "GlmMoeDsaForCausalLM": ["zai-org"],
    "GPT2LMHeadModel": ["openai-community", "stanford-crfm", "Writer"],
    "GPTBigCodeForCausalLM": ["bigcode"],
    "GptOssForCausalLM": ["openai"],
    "GPTJForCausalLM": ["EleutherAI", "togethercomputer"],
    "GPTNeoForCausalLM": ["EleutherAI", "roneneldan"],
    "GPTNeoXForCausalLM": ["EleutherAI", "cyberagent", "stabilityai", "togethercomputer"],
    "GraniteForCausalLM": ["ibm-granite"],
    "GraniteMoeForCausalLM": ["ibm-granite"],
    "GraniteMoeHybridForCausalLM": ["ibm-granite"],
    "HubertForCTC": ["facebook"],
    "HubertModel": ["facebook"],
    "HrmTextForCausalLM": ["sapientinc"],
    "HunYuanDenseV1ForCausalLM": ["tencent"],
    "Idefics3ForConditionalGeneration": ["HuggingFaceM4", "ibm-granite"],
    "InternLM2ForCausalLM": ["internlm"],
    "LEDForConditionalGeneration": ["allenai"],
    "LLaDAModelLM": ["GSAI-ML"],
    "LlamaForCausalLM": ["meta-llama", "huggyllama", "codellama", "SimpleStories"],
    "Llama4ForCausalLM": ["meta-llama", "trl-internal-testing"],
    "Llama4ForConditionalGeneration": ["meta-llama"],
    "LlavaForConditionalGeneration": ["llava-hf"],
    "LlavaNextForConditionalGeneration": ["llava-hf"],
    "LlavaOnevisionForConditionalGeneration": ["llava-hf"],
    "Lfm2ForCausalLM": ["LiquidAI"],
    "Lfm2MoeForCausalLM": ["LiquidAI"],
    "Mamba2ForCausalLM": ["state-spaces"],
    "LongT5ForConditionalGeneration": ["google"],
    "M2M100ForConditionalGeneration": ["facebook"],
    "MambaForCausalLM": ["state-spaces"],
    "MarianMTModel": ["Helsinki-NLP"],
    "MBartForConditionalGeneration": ["facebook"],
    "MiniMaxM2ForCausalLM": ["MiniMaxAI"],
    "NemotronForCausalLM": ["nvidia"],
    "NemotronHForCausalLM": ["nvidia"],
    "MistralForCausalLM": ["mistralai"],
    "Mistral3ForConditionalGeneration": ["mistralai"],
    "MixtralForCausalLM": ["mistralai"],
    "MPTForCausalLM": ["mosaicml"],
    "MptForCausalLM": ["mosaicml"],
    "MT5ForConditionalGeneration": ["google", "bigscience", "csebuetnlp"],
    "Olmo2ForCausalLM": ["allenai", "HPLT"],
    "Olmo3ForCausalLM": ["allenai"],
    "OlmoeForCausalLM": ["allenai"],
    "OlmoHybridForCausalLM": ["allenai"],
    "OlmoForCausalLM": ["allenai"],
    "OpenAIGPTLMHeadModel": ["openai-community"],
    "OpenELMForCausalLM": ["apple"],
    "OPTForCausalLM": ["facebook"],
    "PegasusForConditionalGeneration": ["google"],
    "OuroForCausalLM": ["ByteDance"],
    "Phi3ForCausalLM": ["microsoft"],
    "PhiMoEForCausalLM": ["microsoft"],
    "PhiForCausalLM": ["microsoft"],
    "Qwen2ForCausalLM": ["Qwen", "nvidia"],
    "Qwen2_5_VLForConditionalGeneration": ["Qwen"],
    "Qwen3VLForConditionalGeneration": ["Qwen"],
    "Qwen3VLMoeForConditionalGeneration": ["Qwen"],
    "Qwen2AudioForConditionalGeneration": ["Qwen"],
    "Qwen2MoeForCausalLM": ["Qwen"],
    "Qwen3ForCausalLM": ["Qwen", "nvidia"],
    "Qwen3MoeForCausalLM": ["Qwen"],
    "Qwen3NextForCausalLM": ["Qwen"],
    "Qwen3_5ForCausalLM": ["Qwen"],
    "Qwen3_5ForConditionalGeneration": ["Qwen"],
    "Qwen3_5MoeForCausalLM": ["Qwen"],
    "Qwen3_5MoeForConditionalGeneration": ["Qwen"],
    "QwenForCausalLM": ["Qwen"],
    "RecurrentGemmaForCausalLM": ["google"],
    "SeedOssForCausalLM": ["ByteDance-Seed"],
    "RWKV7ForCausalLM": ["fla-hub"],
    "SmolLM3ForCausalLM": ["HuggingFaceTB"],
    "StableLmForCausalLM": ["stabilityai"],
    "Starcoder2ForCausalLM": ["bigcode"],
    "T5ForConditionalGeneration": ["google-t5", "google", "Salesforce", "MBZUAI"],
    "T5WithLMHeadModel": ["google-t5"],
    "T5GemmaForConditionalGeneration": ["google"],
    "T5Gemma2ForConditionalGeneration": ["google"],
    "XGLMForCausalLM": ["facebook"],
    "Zamba2ForCausalLM": ["Zyphra"],
}

__all__ = [
    # Constants
    "HF_SUPPORTED_ARCHITECTURES",
    "CANONICAL_AUTHORS_BY_ARCH",
    # Exceptions
    "ModelRegistryError",
    "ModelNotFoundError",
    "ArchitectureNotSupportedError",
    "DataNotLoadedError",
    "DataValidationError",
    # Schemas
    "ModelEntry",
    "ModelMetadata",
    "ScanInfo",
    "ArchitectureGap",
    "ArchitectureStats",
    "ArchitectureAnalysis",
    "SupportedModelsReport",
    "ArchitectureGapsReport",
    # Verification
    "VerificationRecord",
    "VerificationHistory",
]
