"""Model Registry tools for TransformerLens.

This package provides tools for discovering and documenting HuggingFace models
that are compatible with TransformerLens.

Main modules:
    - api: Public API for programmatic access to model registry data
    - schemas: Data classes for model entries, architecture gaps, etc.
    - verification: Verification tracking for model compatibility
    - exceptions: Custom exceptions for the model registry

Example usage:
    >>> from transformer_lens.tools.model_registry import api  # doctest: +SKIP
    >>> api.is_model_supported("openai-community/gpt2")  # doctest: +SKIP
    True
    >>> models = api.get_architecture_models("GPT2LMHeadModel")  # doctest: +SKIP
"""

from .exceptions import (
    ArchitectureNotSupportedError,
    DataNotLoadedError,
    DataValidationError,
    ModelNotFoundError,
    ModelRegistryError,
)
from .schemas import (
    ArchitectureAnalysis,
    ArchitectureGap,
    ArchitectureGapsReport,
    ArchitectureStats,
    ModelEntry,
    ModelMetadata,
    ScanInfo,
    SupportedModelsReport,
)
from .verification import VerificationHistory, VerificationRecord

# Canonical set of HuggingFace architecture class names supported by TransformerBridge.
# These must match the exact strings found in HF model config.architectures[]
# and correspond to adapters registered in architecture_adapter_factory.py.
#
# Internal-only architectures (NanoGPT, MinGPT, NeelSoluOld, GPT2LMHeadCustomModel,
# TransformerLensNative) are excluded since they never appear on HuggingFace Hub.
# Factory-internal alias casings (Gemma1, Neo, NeoX) are also excluded since they
# route to canonical adapters but HF reports the canonical names (Gemma, GPTNeo,
# GPTNeoX) in config.architectures instead.
HF_SUPPORTED_ARCHITECTURES: set[str] = {
    "ApertusForCausalLM",
    "ArceeForCausalLM",
    "BaiChuanForCausalLM",
    "BaichuanForCausalLM",
    "BartForConditionalGeneration",
    "BD3LM",
    "BertForMaskedLM",
    "BloomForCausalLM",
    "CodeGenForCausalLM",
    "Cohere2ForCausalLM",
    "CohereForCausalLM",
    "DeepseekV2ForCausalLM",
    "DeepseekV3ForCausalLM",
    "DeepseekV4ForCausalLM",
    "FalconForCausalLM",
    "FalconH1ForCausalLM",
    "GemmaForCausalLM",
    "Gemma2ForCausalLM",
    "Gemma3ForCausalLM",
    "Gemma3ForConditionalGeneration",
    "Gemma3nForConditionalGeneration",
    "Gemma4ForConditionalGeneration",
    "Gemma4UnifiedForConditionalGeneration",
    "Glm4MoeForCausalLM",
    "GlmMoeDsaForCausalLM",
    "GraniteForCausalLM",
    "GraniteMoeForCausalLM",
    "GraniteMoeHybridForCausalLM",
    "GPT2LMHeadModel",
    "GPTBigCodeForCausalLM",
    "GptOssForCausalLM",
    "GPTJForCausalLM",
    "GPTNeoForCausalLM",
    "OpenELMForCausalLM",
    "GPTNeoXForCausalLM",
    "HubertForCTC",
    "HubertModel",
    "HrmTextForCausalLM",
    "HunYuanDenseV1ForCausalLM",
    "InternLM2ForCausalLM",
    "LLaDAModelLM",
    "LlamaForCausalLM",
    "LlavaForConditionalGeneration",
    "LlavaNextForConditionalGeneration",
    "LlavaOnevisionForConditionalGeneration",
    "Lfm2ForCausalLM",
    "Lfm2MoeForCausalLM",
    "MambaForCausalLM",
    "Mamba2ForCausalLM",
    "NemotronHForCausalLM",
    "MPTForCausalLM",
    "MistralForCausalLM",
    "MixtralForCausalLM",
    "Olmo2ForCausalLM",
    "Olmo3ForCausalLM",
    "OlmoForCausalLM",
    "OlmoeForCausalLM",
    "OPTForCausalLM",
    "OuroForCausalLM",
    "PhiForCausalLM",
    "Phi3ForCausalLM",
    "PhiMoEForCausalLM",
    "QwenForCausalLM",
    "Qwen2ForCausalLM",
    "Qwen2MoeForCausalLM",
    "Qwen3ForCausalLM",
    "Qwen3MoeForCausalLM",
    "Qwen3NextForCausalLM",
    "Qwen3_5ForCausalLM",
    "Qwen3_5ForConditionalGeneration",
    "RavenForCausalLM",
    "RecurrentGemmaForCausalLM",
    "RWKV7ForCausalLM",
    "SmolLM3ForCausalLM",
    "StableLmForCausalLM",
    "Starcoder2ForCausalLM",
    "T5ForConditionalGeneration",
    "MT5ForConditionalGeneration",
    "T5GemmaForConditionalGeneration",
    "T5Gemma2ForConditionalGeneration",
    "XGLMForCausalLM",
    "Zamba2ForCausalLM",
}

# Foundation-trained orgs per architecture. Source of truth for the scraper's
# download-threshold bypass and the docs table's "Canonical only" toggle.
CANONICAL_AUTHORS_BY_ARCH: dict[str, list[str]] = {
    "ApertusForCausalLM": ["swiss-ai"],
    "ArceeForCausalLM": ["arcee-ai"],
    "BaiChuanForCausalLM": ["baichuan-inc"],
    "BaichuanForCausalLM": ["baichuan-inc"],
    "BartForConditionalGeneration": ["facebook"],
    "BD3LM": ["kuleshov-group"],
    "BertForMaskedLM": ["google-bert"],
    "BloomForCausalLM": ["bigscience"],
    "CodeGenForCausalLM": ["Salesforce"],
    "Cohere2ForCausalLM": ["CohereLabs"],
    "CohereForCausalLM": ["CohereLabs"],
    "DeepseekV2ForCausalLM": ["deepseek-ai"],
    "DeepseekV3ForCausalLM": ["deepseek-ai"],
    "DeepseekV4ForCausalLM": ["deepseek-ai"],
    "FalconForCausalLM": ["tiiuae"],
    "FalconH1ForCausalLM": ["tiiuae"],
    "Gemma2ForCausalLM": ["google"],
    "Gemma3ForCausalLM": ["google"],
    "Gemma3ForConditionalGeneration": ["google"],
    "Gemma3nForConditionalGeneration": ["google"],
    "Gemma4ForConditionalGeneration": ["google"],
    "Gemma4UnifiedForConditionalGeneration": ["google"],
    "GemmaForCausalLM": ["google"],
    "Glm4MoeForCausalLM": ["zai-org"],
    "GlmMoeDsaForCausalLM": ["zai-org"],
    "GPT2LMHeadModel": ["openai-community", "stanford-crfm", "Writer"],
    "GPTBigCodeForCausalLM": ["bigcode"],
    "GptOssForCausalLM": ["openai"],
    "GPTJForCausalLM": ["EleutherAI", "togethercomputer"],
    "GPTNeoForCausalLM": ["EleutherAI", "roneneldan"],
    "GPTNeoXForCausalLM": ["EleutherAI", "cyberagent", "stabilityai", "togethercomputer"],
    "GraniteForCausalLM": ["ibm-granite"],
    "GraniteMoeForCausalLM": ["ibm-granite"],
    "GraniteMoeHybridForCausalLM": ["ibm-granite"],
    "HubertForCTC": ["facebook"],
    "HubertModel": ["facebook"],
    "HrmTextForCausalLM": ["sapientinc"],
    "HunYuanDenseV1ForCausalLM": ["tencent"],
    "InternLM2ForCausalLM": ["internlm"],
    "LLaDAModelLM": ["GSAI-ML"],
    "LlamaForCausalLM": ["meta-llama", "huggyllama", "codellama", "SimpleStories"],
    "LlavaForConditionalGeneration": ["llava-hf"],
    "LlavaNextForConditionalGeneration": ["llava-hf"],
    "LlavaOnevisionForConditionalGeneration": ["llava-hf"],
    "Lfm2ForCausalLM": ["LiquidAI"],
    "Lfm2MoeForCausalLM": ["LiquidAI"],
    "Mamba2ForCausalLM": ["state-spaces"],
    "MambaForCausalLM": ["state-spaces"],
    "NemotronHForCausalLM": ["nvidia"],
    "MistralForCausalLM": ["mistralai"],
    "MixtralForCausalLM": ["mistralai"],
    "MPTForCausalLM": ["mosaicml"],
    "MT5ForConditionalGeneration": ["google", "bigscience", "csebuetnlp"],
    "Olmo2ForCausalLM": ["allenai", "HPLT"],
    "Olmo3ForCausalLM": ["allenai"],
    "OlmoeForCausalLM": ["allenai"],
    "OlmoForCausalLM": ["allenai"],
    "OpenELMForCausalLM": ["apple"],
    "OPTForCausalLM": ["facebook"],
    "OuroForCausalLM": ["ByteDance"],
    "Phi3ForCausalLM": ["microsoft"],
    "PhiMoEForCausalLM": ["microsoft"],
    "PhiForCausalLM": ["microsoft"],
    "Qwen2ForCausalLM": ["Qwen", "nvidia"],
    "Qwen2MoeForCausalLM": ["Qwen"],
    "Qwen3ForCausalLM": ["Qwen", "nvidia"],
    "Qwen3MoeForCausalLM": ["Qwen"],
    "Qwen3NextForCausalLM": ["Qwen"],
    "Qwen3_5ForCausalLM": ["Qwen"],
    "Qwen3_5ForConditionalGeneration": ["Qwen"],
    "QwenForCausalLM": ["Qwen"],
    "RavenForCausalLM": ["tomg-group-umd"],
    "RecurrentGemmaForCausalLM": ["google"],
    "RWKV7ForCausalLM": ["fla-hub"],
    "SmolLM3ForCausalLM": ["HuggingFaceTB"],
    "StableLmForCausalLM": ["stabilityai"],
    "Starcoder2ForCausalLM": ["bigcode"],
    "T5ForConditionalGeneration": ["google-t5", "google", "Salesforce", "MBZUAI"],
    "T5GemmaForConditionalGeneration": ["google"],
    "T5Gemma2ForConditionalGeneration": ["google"],
    "XGLMForCausalLM": ["facebook"],
    "Zamba2ForCausalLM": ["Zyphra"],
}

__all__ = [
    # Constants
    "HF_SUPPORTED_ARCHITECTURES",
    "CANONICAL_AUTHORS_BY_ARCH",
    # Exceptions
    "ModelRegistryError",
    "ModelNotFoundError",
    "ArchitectureNotSupportedError",
    "DataNotLoadedError",
    "DataValidationError",
    # Schemas
    "ModelEntry",
    "ModelMetadata",
    "ScanInfo",
    "ArchitectureGap",
    "ArchitectureStats",
    "ArchitectureAnalysis",
    "SupportedModelsReport",
    "ArchitectureGapsReport",
    # Verification
    "VerificationRecord",
    "VerificationHistory",
]
