# save 100 prompts for reloading purposes

prompts = [{'text': 'Then, Erin and Laura were working at the school. Laura decided to give a snack to Erin',
  'IO': 'Erin',
  'S': 'Laura',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Mark and Michael had a lot of fun at the house. Michael gave a snack to Mark',
  'IO': 'Mark',
  'S': 'Michael',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Anthony and Erin were working at the restaurant. Erin decided to give a drink to Anthony',
  'IO': 'Anthony',
  'S': 'Erin',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Bryan and Courtney had a lot of fun at the station. Bryan gave a necklace to Courtney',
  'IO': 'Courtney',
  'S': 'Bryan',
  'TEMPLATE_IDX': 11},
 {'text': 'When Rachel and Stephen got a kiss at the office, Rachel decided to give it to Stephen',
  'IO': 'Stephen',
  'S': 'Rachel',
  'TEMPLATE_IDX': 6},
 {'text': 'When Shannon and Paul got a computer at the store, Shannon decided to give it to Paul',
  'IO': 'Paul',
  'S': 'Shannon',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Richard and Travis were working at the school. Richard decided to give a necklace to Travis',
  'IO': 'Travis',
  'S': 'Richard',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Bryan and William were thinking about going to the school. Bryan wanted to give a ring to William',
  'IO': 'William',
  'S': 'Bryan',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Shannon and Megan had a long argument, and afterwards Shannon said to Megan',
  'IO': 'Megan',
  'S': 'Shannon',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Jennifer and Sara were working at the school. Jennifer decided to give a bone to Sara',
  'IO': 'Sara',
  'S': 'Jennifer',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Christine and Shannon went to the restaurant. Shannon gave a bone to Christine',
  'IO': 'Christine',
  'S': 'Shannon',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Melissa and Kimberly were thinking about going to the house. Kimberly wanted to give a bone to Melissa',
  'IO': 'Melissa',
  'S': 'Kimberly',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Stephen and Scott were thinking about going to the station. Stephen wanted to give a basketball to Scott',
  'IO': 'Scott',
  'S': 'Stephen',
  'TEMPLATE_IDX': 8},
 {'text': 'After Timothy and Melissa went to the school, Timothy gave a computer to Melissa',
  'IO': 'Melissa',
  'S': 'Timothy',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Allison and Sara went to the restaurant. Allison gave a snack to Sara',
  'IO': 'Sara',
  'S': 'Allison',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Katherine and Benjamin had a lot of fun at the office. Benjamin gave a snack to Katherine',
  'IO': 'Katherine',
  'S': 'Benjamin',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Benjamin and Lisa went to the school. Lisa gave a snack to Benjamin',
  'IO': 'Benjamin',
  'S': 'Lisa',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Cody and Eric went to the house. Eric gave a bone to Cody',
  'IO': 'Cody',
  'S': 'Eric',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Kevin and Jennifer had a lot of fun at the school. Kevin gave a computer to Jennifer',
  'IO': 'Jennifer',
  'S': 'Kevin',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, David and Sean went to the garden. Sean gave a ring to David',
  'IO': 'David',
  'S': 'Sean',
  'TEMPLATE_IDX': 13},
 {'text': 'After Tiffany and Adam went to the garden, Tiffany gave a computer to Adam',
  'IO': 'Adam',
  'S': 'Tiffany',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Kristen and Jessica were thinking about going to the station. Jessica wanted to give a snack to Kristen',
  'IO': 'Kristen',
  'S': 'Jessica',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Jennifer and Tiffany had a long argument, and afterwards Tiffany said to Jennifer',
  'IO': 'Jennifer',
  'S': 'Tiffany',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Dustin and Shannon went to the restaurant. Dustin gave a computer to Shannon',
  'IO': 'Shannon',
  'S': 'Dustin',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Brandon and Emily were thinking about going to the office. Brandon wanted to give a drink to Emily',
  'IO': 'Emily',
  'S': 'Brandon',
  'TEMPLATE_IDX': 8},
 {'text': 'After Jamie and Nicole went to the station, Jamie gave a computer to Nicole',
  'IO': 'Nicole',
  'S': 'Jamie',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Sean and Paul were working at the office. Sean decided to give a kiss to Paul',
  'IO': 'Paul',
  'S': 'Sean',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Danielle and Anthony were thinking about going to the station. Anthony wanted to give a basketball to Danielle',
  'IO': 'Danielle',
  'S': 'Anthony',
  'TEMPLATE_IDX': 1},
 {'text': 'When Rebecca and Mary got a ring at the garden, Rebecca decided to give it to Mary',
  'IO': 'Mary',
  'S': 'Rebecca',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Benjamin and Vanessa had a lot of fun at the garden. Benjamin gave a snack to Vanessa',
  'IO': 'Vanessa',
  'S': 'Benjamin',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Andrea and Kyle were working at the house. Andrea decided to give a drink to Kyle',
  'IO': 'Kyle',
  'S': 'Andrea',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Jeremy and Elizabeth had a lot of fun at the store. Elizabeth gave a ring to Jeremy',
  'IO': 'Jeremy',
  'S': 'Elizabeth',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Andrew and Kenneth went to the house. Kenneth gave a necklace to Andrew',
  'IO': 'Andrew',
  'S': 'Kenneth',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Nicholas and Elizabeth were working at the office. Elizabeth decided to give a ring to Nicholas',
  'IO': 'Nicholas',
  'S': 'Elizabeth',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Nathan and Sara had a lot of fun at the store. Nathan gave a kiss to Sara',
  'IO': 'Sara',
  'S': 'Nathan',
  'TEMPLATE_IDX': 11},
 {'text': 'After Joseph and Patrick went to the restaurant, Joseph gave a ring to Patrick',
  'IO': 'Patrick',
  'S': 'Joseph',
  'TEMPLATE_IDX': 0},
 {'text': 'After Melissa and Jason went to the restaurant, Jason gave a drink to Melissa',
  'IO': 'Melissa',
  'S': 'Jason',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Bradley and Lindsey had a lot of fun at the office. Bradley gave a bone to Lindsey',
  'IO': 'Lindsey',
  'S': 'Bradley',
  'TEMPLATE_IDX': 11},
 {'text': 'When Jesse and Aaron got a necklace at the station, Aaron decided to give it to Jesse',
  'IO': 'Jesse',
  'S': 'Aaron',
  'TEMPLATE_IDX': 4},
 {'text': 'After Christopher and Cody went to the station, Cody gave a necklace to Christopher',
  'IO': 'Christopher',
  'S': 'Cody',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Brittany and Joshua were working at the hospital. Brittany decided to give a bone to Joshua',
  'IO': 'Joshua',
  'S': 'Brittany',
  'TEMPLATE_IDX': 2},
 {'text': 'When Paul and Tyler got a ring at the garden, Paul decided to give it to Tyler',
  'IO': 'Tyler',
  'S': 'Paul',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Anthony and Angela were thinking about going to the store. Angela wanted to give a basketball to Anthony',
  'IO': 'Anthony',
  'S': 'Angela',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Erica and Sean were working at the school. Sean decided to give a kiss to Erica',
  'IO': 'Erica',
  'S': 'Sean',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Travis and Nicholas had a lot of fun at the office. Nicholas gave a necklace to Travis',
  'IO': 'Travis',
  'S': 'Nicholas',
  'TEMPLATE_IDX': 5},
 {'text': 'After Laura and John went to the house, Laura gave a basketball to John',
  'IO': 'John',
  'S': 'Laura',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Cody and Robert went to the school. Cody gave a basketball to Robert',
  'IO': 'Robert',
  'S': 'Cody',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Jesse and Paul were working at the house. Jesse decided to give a necklace to Paul',
  'IO': 'Paul',
  'S': 'Jesse',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Lindsay and Kenneth went to the station. Lindsay gave a necklace to Kenneth',
  'IO': 'Kenneth',
  'S': 'Lindsay',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Michelle and Mary were thinking about going to the store. Mary wanted to give a snack to Michelle',
  'IO': 'Michelle',
  'S': 'Mary',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Kyle and Laura had a lot of fun at the hospital. Kyle gave a kiss to Laura',
  'IO': 'Laura',
  'S': 'Kyle',
  'TEMPLATE_IDX': 11},
 {'text': 'When Courtney and Erin got a drink at the station, Erin decided to give it to Courtney',
  'IO': 'Courtney',
  'S': 'Erin',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Ashley and Joshua had a long argument, and afterwards Ashley said to Joshua',
  'IO': 'Joshua',
  'S': 'Ashley',
  'TEMPLATE_IDX': 7},
 {'text': 'After Danielle and Shannon went to the house, Shannon gave a bone to Danielle',
  'IO': 'Danielle',
  'S': 'Shannon',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Stephen and Rachel had a long argument, and afterwards Rachel said to Stephen',
  'IO': 'Stephen',
  'S': 'Rachel',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Jonathan and Jessica were working at the station. Jonathan decided to give a necklace to Jessica',
  'IO': 'Jessica',
  'S': 'Jonathan',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Ashley and Jeffrey went to the hospital. Ashley gave a necklace to Jeffrey',
  'IO': 'Jeffrey',
  'S': 'Ashley',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Erin and Nicholas were working at the house. Nicholas decided to give a drink to Erin',
  'IO': 'Erin',
  'S': 'Nicholas',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Kimberly and Jeffrey were working at the garden. Jeffrey decided to give a ring to Kimberly',
  'IO': 'Kimberly',
  'S': 'Jeffrey',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Brittany and Ashley had a lot of fun at the hospital. Brittany gave a necklace to Ashley',
  'IO': 'Ashley',
  'S': 'Brittany',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Joseph and Steven had a long argument, and afterwards Joseph said to Steven',
  'IO': 'Steven',
  'S': 'Joseph',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Scott and Rebecca had a long argument, and afterwards Rebecca said to Scott',
  'IO': 'Scott',
  'S': 'Rebecca',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Brittany and Katie had a long argument, and afterwards Katie said to Brittany',
  'IO': 'Brittany',
  'S': 'Katie',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Aaron and Jonathan were thinking about going to the garden. Jonathan wanted to give a bone to Aaron',
  'IO': 'Aaron',
  'S': 'Jonathan',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Erica and Tyler were thinking about going to the restaurant. Erica wanted to give a snack to Tyler',
  'IO': 'Tyler',
  'S': 'Erica',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Jose and Joseph had a lot of fun at the office. Jose gave a kiss to Joseph',
  'IO': 'Joseph',
  'S': 'Jose',
  'TEMPLATE_IDX': 11},
 {'text': 'After Lisa and Courtney went to the store, Lisa gave a drink to Courtney',
  'IO': 'Courtney',
  'S': 'Lisa',
  'TEMPLATE_IDX': 0},
 {'text': 'After Danielle and Eric went to the school, Danielle gave a computer to Eric',
  'IO': 'Eric',
  'S': 'Danielle',
  'TEMPLATE_IDX': 0},
 {'text': 'When Mary and Megan got a bone at the garden, Mary decided to give it to Megan',
  'IO': 'Megan',
  'S': 'Mary',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Mark and Alexander were working at the garden. Mark decided to give a drink to Alexander',
  'IO': 'Alexander',
  'S': 'Mark',
  'TEMPLATE_IDX': 2},
 {'text': 'When Patrick and Kelly got a computer at the office, Patrick decided to give it to Kelly',
  'IO': 'Kelly',
  'S': 'Patrick',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Matthew and Benjamin were working at the station. Matthew decided to give a snack to Benjamin',
  'IO': 'Benjamin',
  'S': 'Matthew',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Lauren and Jason had a lot of fun at the school. Lauren gave a bone to Jason',
  'IO': 'Jason',
  'S': 'Lauren',
  'TEMPLATE_IDX': 11},
 {'text': 'When Steven and Danielle got a drink at the office, Danielle decided to give it to Steven',
  'IO': 'Steven',
  'S': 'Danielle',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Lisa and Richard were thinking about going to the restaurant. Richard wanted to give a snack to Lisa',
  'IO': 'Lisa',
  'S': 'Richard',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Kyle and Cody went to the garden. Kyle gave a snack to Cody',
  'IO': 'Cody',
  'S': 'Kyle',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Thomas and James had a long argument, and afterwards Thomas said to James',
  'IO': 'James',
  'S': 'Thomas',
  'TEMPLATE_IDX': 7},
 {'text': 'When Lindsay and Amber got a computer at the school, Amber decided to give it to Lindsay',
  'IO': 'Lindsay',
  'S': 'Amber',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Courtney and Anthony had a lot of fun at the garden. Courtney gave a bone to Anthony',
  'IO': 'Anthony',
  'S': 'Courtney',
  'TEMPLATE_IDX': 11},
 {'text': 'When Katie and Andrew got a basketball at the school, Katie decided to give it to Andrew',
  'IO': 'Andrew',
  'S': 'Katie',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Samuel and Christine were working at the restaurant. Christine decided to give a ring to Samuel',
  'IO': 'Samuel',
  'S': 'Christine',
  'TEMPLATE_IDX': 12},
 {'text': 'After Gregory and Sean went to the garden, Gregory gave a basketball to Sean',
  'IO': 'Sean',
  'S': 'Gregory',
  'TEMPLATE_IDX': 0},
 {'text': 'When Ashley and Adam got a drink at the restaurant, Adam decided to give it to Ashley',
  'IO': 'Ashley',
  'S': 'Adam',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Samantha and Sara had a long argument, and afterwards Samantha said to Sara',
  'IO': 'Sara',
  'S': 'Samantha',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Amanda and Kevin went to the garden. Kevin gave a bone to Amanda',
  'IO': 'Amanda',
  'S': 'Kevin',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Andrew and Crystal had a long argument, and afterwards Crystal said to Andrew',
  'IO': 'Andrew',
  'S': 'Crystal',
  'TEMPLATE_IDX': 10},
 {'text': 'When Sean and Richard got a bone at the store, Sean decided to give it to Richard',
  'IO': 'Richard',
  'S': 'Sean',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Daniel and Christine had a lot of fun at the restaurant. Christine gave a kiss to Daniel',
  'IO': 'Daniel',
  'S': 'Christine',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Laura and Michelle went to the office. Laura gave a bone to Michelle',
  'IO': 'Michelle',
  'S': 'Laura',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Amber and Matthew were working at the station. Amber decided to give a ring to Matthew',
  'IO': 'Matthew',
  'S': 'Amber',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, John and Scott went to the store. John gave a computer to Scott',
  'IO': 'Scott',
  'S': 'John',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Katherine and Shannon had a lot of fun at the school. Shannon gave a basketball to Katherine',
  'IO': 'Katherine',
  'S': 'Shannon',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Elizabeth and Kimberly were thinking about going to the house. Elizabeth wanted to give a basketball to Kimberly',
  'IO': 'Kimberly',
  'S': 'Elizabeth',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Vanessa and Ryan were thinking about going to the house. Vanessa wanted to give a ring to Ryan',
  'IO': 'Ryan',
  'S': 'Vanessa',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Vanessa and Scott had a lot of fun at the garden. Vanessa gave a drink to Scott',
  'IO': 'Scott',
  'S': 'Vanessa',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Christina and Sarah had a lot of fun at the garden. Christina gave a snack to Sarah',
  'IO': 'Sarah',
  'S': 'Christina',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Bryan and Elizabeth were thinking about going to the office. Elizabeth wanted to give a computer to Bryan',
  'IO': 'Bryan',
  'S': 'Elizabeth',
  'TEMPLATE_IDX': 1},
 {'text': 'When Robert and Gregory got a basketball at the garden, Robert decided to give it to Gregory',
  'IO': 'Gregory',
  'S': 'Robert',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Tyler and Samuel had a long argument, and afterwards Samuel said to Tyler',
  'IO': 'Tyler',
  'S': 'Samuel',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Thomas and Brandon were thinking about going to the store. Brandon wanted to give a kiss to Thomas',
  'IO': 'Thomas',
  'S': 'Brandon',
  'TEMPLATE_IDX': 1}]