[{'text': 'Then, Matthew and Kyle were working at the hospital. Kyle decided to give a ring to Matthew',
  'IO': 'Matthew',
  'S': 'Kyle',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Rachel and Lisa went to the station. Rachel gave a computer to Lisa',
  'IO': 'Lisa',
  'S': 'Rachel',
  'TEMPLATE_IDX': 6},
 {'text': 'When Richard and Joseph got a necklace at the station, Richard decided to give it to Joseph',
  'IO': 'Joseph',
  'S': 'Richard',
  'TEMPLATE_IDX': 2},
 {'text': 'After Sean and Amanda went to the office, Amanda gave a kiss to Sean',
  'IO': 'Sean',
  'S': 'Amanda',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Jason and Kenneth were thinking about going to the hospital. Kenneth wanted to give a basketball to Jason',
  'IO': 'Jason',
  'S': 'Kenneth',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Kristen and Bradley were thinking about going to the restaurant. Bradley wanted to give a basketball to Kristen',
  'IO': 'Kristen',
  'S': 'Bradley',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Patrick and Alexander had a long argument, and afterwards Alexander said to Patrick',
  'IO': 'Patrick',
  'S': 'Alexander',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Dustin and Timothy had a lot of fun at the hospital. Dustin gave a kiss to Timothy',
  'IO': 'Timothy',
  'S': 'Dustin',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, William and Patrick were thinking about going to the station. William wanted to give a necklace to Patrick',
  'IO': 'Patrick',
  'S': 'William',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Robert and Jeffrey were working at the station. Robert decided to give a necklace to Jeffrey',
  'IO': 'Jeffrey',
  'S': 'Robert',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Brandon and Emily went to the office. Emily gave a necklace to Brandon',
  'IO': 'Brandon',
  'S': 'Emily',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Rebecca and Laura had a lot of fun at the garden. Laura gave a kiss to Rebecca',
  'IO': 'Rebecca',
  'S': 'Laura',
  'TEMPLATE_IDX': 0},
 {'text': 'After Jonathan and Elizabeth went to the restaurant, Jonathan gave a ring to Elizabeth',
  'IO': 'Elizabeth',
  'S': 'Jonathan',
  'TEMPLATE_IDX': 8},
 {'text': 'When Joshua and Rebecca got a snack at the office, Joshua decided to give it to Rebecca',
  'IO': 'Rebecca',
  'S': 'Joshua',
  'TEMPLATE_IDX': 2},
 {'text': 'When Tyler and Courtney got a kiss at the station, Courtney decided to give it to Tyler',
  'IO': 'Tyler',
  'S': 'Courtney',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Adam and Amy went to the garden. Amy gave a basketball to Adam',
  'IO': 'Adam',
  'S': 'Amy',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Jesse and Brian went to the garden. Jesse gave a snack to Brian',
  'IO': 'Brian',
  'S': 'Jesse',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Kenneth and John were working at the office. Kenneth decided to give a drink to John',
  'IO': 'John',
  'S': 'Kenneth',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, William and Megan went to the station. Megan gave a snack to William',
  'IO': 'William',
  'S': 'Megan',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Brittany and Lindsay were working at the school. Lindsay decided to give a drink to Brittany',
  'IO': 'Brittany',
  'S': 'Lindsay',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Andrea and Tiffany were working at the house. Andrea decided to give a drink to Tiffany',
  'IO': 'Tiffany',
  'S': 'Andrea',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Anthony and Lindsay were thinking about going to the hospital. Lindsay wanted to give a necklace to Anthony',
  'IO': 'Anthony',
  'S': 'Lindsay',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Kevin and Patrick had a long argument, and afterwards Patrick said to Kevin',
  'IO': 'Kevin',
  'S': 'Patrick',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Brandon and Elizabeth went to the hospital. Brandon gave a snack to Elizabeth',
  'IO': 'Elizabeth',
  'S': 'Brandon',
  'TEMPLATE_IDX': 6},
 {'text': 'When Stephanie and Kenneth got a basketball at the office, Stephanie decided to give it to Kenneth',
  'IO': 'Kenneth',
  'S': 'Stephanie',
  'TEMPLATE_IDX': 2},
 {'text': 'After Andrea and Jeremy went to the store, Andrea gave a basketball to Jeremy',
  'IO': 'Jeremy',
  'S': 'Andrea',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Jason and Anthony went to the restaurant. Jason gave a computer to Anthony',
  'IO': 'Anthony',
  'S': 'Jason',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Patrick and Gregory were working at the station. Patrick decided to give a kiss to Gregory',
  'IO': 'Gregory',
  'S': 'Patrick',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Brian and Travis had a long argument, and afterwards Travis said to Brian',
  'IO': 'Brian',
  'S': 'Travis',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Robert and Christina went to the house. Christina gave a computer to Robert',
  'IO': 'Robert',
  'S': 'Christina',
  'TEMPLATE_IDX': 3},
 {'text': 'After Kenneth and Lauren went to the garden, Kenneth gave a ring to Lauren',
  'IO': 'Lauren',
  'S': 'Kenneth',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, William and Jamie had a lot of fun at the restaurant. William gave a necklace to Jamie',
  'IO': 'Jamie',
  'S': 'William',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Charles and Amy had a lot of fun at the restaurant. Charles gave a bone to Amy',
  'IO': 'Amy',
  'S': 'Charles',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Charles and Sara were thinking about going to the office. Sara wanted to give a bone to Charles',
  'IO': 'Charles',
  'S': 'Sara',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Erica and Matthew had a lot of fun at the hospital. Matthew gave a basketball to Erica',
  'IO': 'Erica',
  'S': 'Matthew',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Joseph and Stephanie were thinking about going to the station. Joseph wanted to give a snack to Stephanie',
  'IO': 'Stephanie',
  'S': 'Joseph',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Lindsey and Kelly had a long argument, and afterwards Lindsey said to Kelly',
  'IO': 'Kelly',
  'S': 'Lindsey',
  'TEMPLATE_IDX': 1},
 {'text': 'After Jesse and Timothy went to the house, Jesse gave a snack to Timothy',
  'IO': 'Timothy',
  'S': 'Jesse',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Daniel and Charles had a lot of fun at the station. Daniel gave a computer to Charles',
  'IO': 'Charles',
  'S': 'Daniel',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Christina and Brian had a lot of fun at the store. Brian gave a drink to Christina',
  'IO': 'Christina',
  'S': 'Brian',
  'TEMPLATE_IDX': 0},
 {'text': 'When Dustin and Michelle got a snack at the restaurant, Michelle decided to give it to Dustin',
  'IO': 'Dustin',
  'S': 'Michelle',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Brandon and Bryan were working at the hospital. Bryan decided to give a drink to Brandon',
  'IO': 'Brandon',
  'S': 'Bryan',
  'TEMPLATE_IDX': 5},
 {'text': 'When Megan and Justin got a basketball at the house, Megan decided to give it to Justin',
  'IO': 'Justin',
  'S': 'Megan',
  'TEMPLATE_IDX': 2},
 {'text': 'When Cody and Sarah got a drink at the hospital, Cody decided to give it to Sarah',
  'IO': 'Sarah',
  'S': 'Cody',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Andrea and Daniel were thinking about going to the school. Daniel wanted to give a snack to Andrea',
  'IO': 'Andrea',
  'S': 'Daniel',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Emily and Richard were thinking about going to the garden. Emily wanted to give a kiss to Richard',
  'IO': 'Richard',
  'S': 'Emily',
  'TEMPLATE_IDX': 12},
 {'text': 'When Alicia and Brandon got a ring at the station, Brandon decided to give it to Alicia',
  'IO': 'Alicia',
  'S': 'Brandon',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Jesse and Katherine went to the house. Jesse gave a snack to Katherine',
  'IO': 'Katherine',
  'S': 'Jesse',
  'TEMPLATE_IDX': 6},
 {'text': 'When Nathan and Michelle got a necklace at the restaurant, Nathan decided to give it to Michelle',
  'IO': 'Michelle',
  'S': 'Nathan',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Allison and Kimberly were thinking about going to the station. Allison wanted to give a necklace to Kimberly',
  'IO': 'Kimberly',
  'S': 'Allison',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Courtney and Brandon were working at the school. Courtney decided to give a computer to Brandon',
  'IO': 'Brandon',
  'S': 'Courtney',
  'TEMPLATE_IDX': 9},
 {'text': 'When William and Kimberly got a snack at the restaurant, William decided to give it to Kimberly',
  'IO': 'Kimberly',
  'S': 'William',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Megan and Michael were thinking about going to the garden. Michael wanted to give a basketball to Megan',
  'IO': 'Megan',
  'S': 'Michael',
  'TEMPLATE_IDX': 13},
 {'text': 'When Joseph and Samantha got a ring at the house, Samantha decided to give it to Joseph',
  'IO': 'Joseph',
  'S': 'Samantha',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Brian and Lisa had a lot of fun at the store. Brian gave a computer to Lisa',
  'IO': 'Lisa',
  'S': 'Brian',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, Nicole and Rachel had a lot of fun at the hospital. Nicole gave a drink to Rachel',
  'IO': 'Rachel',
  'S': 'Nicole',
  'TEMPLATE_IDX': 4},
 {'text': 'After Ashley and Andrea went to the station, Ashley gave a ring to Andrea',
  'IO': 'Andrea',
  'S': 'Ashley',
  'TEMPLATE_IDX': 8},
 {'text': 'After Eric and Kelly went to the house, Eric gave a basketball to Kelly',
  'IO': 'Kelly',
  'S': 'Eric',
  'TEMPLATE_IDX': 8},
 {'text': 'After Rachel and Richard went to the store, Rachel gave a basketball to Richard',
  'IO': 'Richard',
  'S': 'Rachel',
  'TEMPLATE_IDX': 8},
 {'text': 'Then, Kevin and Ryan had a long argument, and afterwards Kevin said to Ryan',
  'IO': 'Ryan',
  'S': 'Kevin',
  'TEMPLATE_IDX': 1},
 {'text': 'When Tiffany and Lindsay got a drink at the office, Lindsay decided to give it to Tiffany',
  'IO': 'Tiffany',
  'S': 'Lindsay',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Andrea and Benjamin were working at the school. Benjamin decided to give a ring to Andrea',
  'IO': 'Andrea',
  'S': 'Benjamin',
  'TEMPLATE_IDX': 5},
 {'text': 'When Lauren and Courtney got a basketball at the house, Lauren decided to give it to Courtney',
  'IO': 'Courtney',
  'S': 'Lauren',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Elizabeth and Kyle were working at the school. Elizabeth decided to give a necklace to Kyle',
  'IO': 'Kyle',
  'S': 'Elizabeth',
  'TEMPLATE_IDX': 9},
 {'text': 'When Samantha and Sarah got a necklace at the store, Samantha decided to give it to Sarah',
  'IO': 'Sarah',
  'S': 'Samantha',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Andrew and Jonathan had a long argument, and afterwards Jonathan said to Andrew',
  'IO': 'Andrew',
  'S': 'Jonathan',
  'TEMPLATE_IDX': 7},
 {'text': 'Then, Steven and Elizabeth were thinking about going to the office. Steven wanted to give a drink to Elizabeth',
  'IO': 'Elizabeth',
  'S': 'Steven',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Allison and Megan went to the store. Megan gave a snack to Allison',
  'IO': 'Allison',
  'S': 'Megan',
  'TEMPLATE_IDX': 3},
 {'text': 'After Matthew and Alicia went to the house, Alicia gave a basketball to Matthew',
  'IO': 'Matthew',
  'S': 'Alicia',
  'TEMPLATE_IDX': 10},
 {'text': 'Then, Jonathan and Kyle went to the school. Jonathan gave a bone to Kyle',
  'IO': 'Kyle',
  'S': 'Jonathan',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Crystal and Thomas were working at the restaurant. Thomas decided to give a kiss to Crystal',
  'IO': 'Crystal',
  'S': 'Thomas',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Tiffany and Emily went to the school. Emily gave a kiss to Tiffany',
  'IO': 'Tiffany',
  'S': 'Emily',
  'TEMPLATE_IDX': 3},
 {'text': 'When Charles and Amanda got a ring at the store, Amanda decided to give it to Charles',
  'IO': 'Charles',
  'S': 'Amanda',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Michael and Kelly were working at the restaurant. Michael decided to give a necklace to Kelly',
  'IO': 'Kelly',
  'S': 'Michael',
  'TEMPLATE_IDX': 9},
 {'text': 'Then, Megan and Shannon were thinking about going to the station. Megan wanted to give a computer to Shannon',
  'IO': 'Shannon',
  'S': 'Megan',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Jason and Lindsey went to the hospital. Lindsey gave a basketball to Jason',
  'IO': 'Jason',
  'S': 'Lindsey',
  'TEMPLATE_IDX': 3},
 {'text': 'When Sean and Kimberly got a ring at the house, Sean decided to give it to Kimberly',
  'IO': 'Kimberly',
  'S': 'Sean',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Amanda and Bryan had a long argument, and afterwards Amanda said to Bryan',
  'IO': 'Bryan',
  'S': 'Amanda',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Kenneth and Dustin had a lot of fun at the house. Kenneth gave a snack to Dustin',
  'IO': 'Dustin',
  'S': 'Kenneth',
  'TEMPLATE_IDX': 4},
 {'text': 'When Joshua and Stephanie got a necklace at the restaurant, Stephanie decided to give it to Joshua',
  'IO': 'Joshua',
  'S': 'Stephanie',
  'TEMPLATE_IDX': 11},
 {'text': 'Then, Scott and Lauren had a long argument, and afterwards Scott said to Lauren',
  'IO': 'Lauren',
  'S': 'Scott',
  'TEMPLATE_IDX': 1},
 {'text': 'When Laura and Jesse got a snack at the school, Laura decided to give it to Jesse',
  'IO': 'Jesse',
  'S': 'Laura',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Jamie and Jessica were working at the hospital. Jessica decided to give a basketball to Jamie',
  'IO': 'Jamie',
  'S': 'Jessica',
  'TEMPLATE_IDX': 5},
 {'text': 'Then, Joshua and Erica were thinking about going to the school. Joshua wanted to give a necklace to Erica',
  'IO': 'Erica',
  'S': 'Joshua',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Melissa and Patrick had a lot of fun at the store. Patrick gave a basketball to Melissa',
  'IO': 'Melissa',
  'S': 'Patrick',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, William and Jesse went to the office. William gave a necklace to Jesse',
  'IO': 'Jesse',
  'S': 'William',
  'TEMPLATE_IDX': 6},
 {'text': 'Then, Bryan and Laura had a lot of fun at the office. Laura gave a ring to Bryan',
  'IO': 'Bryan',
  'S': 'Laura',
  'TEMPLATE_IDX': 0},
 {'text': 'Then, Travis and Nathan went to the garden. Nathan gave a snack to Travis',
  'IO': 'Travis',
  'S': 'Nathan',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Richard and Travis were thinking about going to the school. Richard wanted to give a kiss to Travis',
  'IO': 'Travis',
  'S': 'Richard',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Brian and Jeffrey were thinking about going to the house. Brian wanted to give a drink to Jeffrey',
  'IO': 'Jeffrey',
  'S': 'Brian',
  'TEMPLATE_IDX': 12},
 {'text': 'Then, Jason and Kyle were thinking about going to the house. Kyle wanted to give a kiss to Jason',
  'IO': 'Jason',
  'S': 'Kyle',
  'TEMPLATE_IDX': 13},
 {'text': 'Then, Katherine and Nathan went to the house. Nathan gave a snack to Katherine',
  'IO': 'Katherine',
  'S': 'Nathan',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Heather and Ryan had a lot of fun at the house. Heather gave a snack to Ryan',
  'IO': 'Ryan',
  'S': 'Heather',
  'TEMPLATE_IDX': 4},
 {'text': 'Then, John and Samuel went to the hospital. Samuel gave a drink to John',
  'IO': 'John',
  'S': 'Samuel',
  'TEMPLATE_IDX': 3},
 {'text': 'Then, Michael and Elizabeth went to the station. Michael gave a snack to Elizabeth',
  'IO': 'Elizabeth',
  'S': 'Michael',
  'TEMPLATE_IDX': 6},
 {'text': 'When Justin and Timothy got a kiss at the house, Justin decided to give it to Timothy',
  'IO': 'Timothy',
  'S': 'Justin',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Amber and Rachel had a long argument, and afterwards Amber said to Rachel',
  'IO': 'Rachel',
  'S': 'Amber',
  'TEMPLATE_IDX': 1},
 {'text': 'Then, Mark and James had a long argument, and afterwards Mark said to James',
  'IO': 'James',
  'S': 'Mark',
  'TEMPLATE_IDX': 1},
 {'text': 'When Jacob and Sarah got a snack at the office, Jacob decided to give it to Sarah',
  'IO': 'Sarah',
  'S': 'Jacob',
  'TEMPLATE_IDX': 2},
 {'text': 'Then, Nathan and Brandon were thinking about going to the restaurant. Nathan wanted to give a drink to Brandon',
  'IO': 'Brandon',
  'S': 'Nathan',
  'TEMPLATE_IDX': 12}]