"""Joint QKV attention bridge with position embeddings support.

This module provides an attention bridge for models that use both:
1. Fused QKV matrices (like Pythia)
2. Position embeddings like RoPE (Rotary Position Embeddings)
"""
from __future__ import annotations

from typing import Any, Callable, Dict, Optional

import torch

from transformer_lens.model_bridge.generalized_components.joint_qkv_attention import (
    JointQKVAttentionBridge,
)
from transformer_lens.model_bridge.generalized_components.position_embedding_hooks_mixin import (
    PositionEmbeddingHooksMixin,
)


class JointQKVPositionEmbeddingsAttentionBridge(
    PositionEmbeddingHooksMixin, JointQKVAttentionBridge
):
    """Attention bridge for models with fused QKV and position embeddings (e.g., Pythia).

    This combines the functionality of JointQKVAttentionBridge (splitting fused QKV matrices)
    with position embeddings support (for models using RoPE).

    The position_embeddings are generated by calling the model's rotary_emb
    component with dummy Q/K tensors and position_ids.
    """

    def __init__(
        self,
        name: str,
        config: Any,
        split_qkv_matrix: Optional[Callable] = None,
        submodules: Optional[Dict[str, Any]] = None,
        **kwargs,
    ):
        """Initialize Joint QKV Position Embeddings attention bridge.

        Args:
            name: Component name
            config: Model configuration
            split_qkv_matrix: Optional function to split the qkv matrix
            submodules: Dictionary of subcomponents
            **kwargs: Additional arguments passed to JointQKVAttentionBridge
        """
        # Ensure position embeddings are required
        kwargs["requires_position_embeddings"] = True
        super().__init__(
            name=name,
            config=config,
            split_qkv_matrix=split_qkv_matrix,
            submodules=submodules,
            **kwargs,
        )
        self._init_position_embedding_hooks()

    def get_random_inputs(
        self,
        batch_size: int = 2,
        seq_len: int = 8,
        device: Optional[torch.device] = None,
        dtype: Optional[torch.dtype] = None,
    ) -> Dict[str, Any]:
        """Generate random inputs for component testing.

        For models using RoPE, position_embeddings are generated by calling rotary_emb
        which returns a tuple of (cos, sin) tensors.

        Args:
            batch_size: Batch size for generated inputs
            seq_len: Sequence length for generated inputs
            device: Device to place tensors on
            dtype: Dtype for generated tensors

        Returns:
            Dictionary with keys: hidden_states, position_embeddings, attention_mask
        """
        if device is None:
            device = torch.device("cpu")
        if dtype is None:
            dtype = torch.float32

        d_model = self.config.d_model if self.config and hasattr(self.config, "d_model") else 512
        inputs: Dict[str, Any] = {
            "hidden_states": torch.randn(batch_size, seq_len, d_model, device=device, dtype=dtype)
        }

        num_heads = (
            self.config.num_attention_heads
            if self.config and hasattr(self.config, "num_attention_heads")
            else self.config.n_heads
            if self.config and hasattr(self.config, "n_heads")
            else 8
        )
        head_dim = (
            self.config.head_dim
            if self.config and hasattr(self.config, "head_dim")
            else (d_model // num_heads)
        )

        # Generate position_embeddings using rotary_emb if available
        if self._rotary_emb is not None:
            try:
                # For GPT-NeoX/Pythia rotary embeddings
                # rotary_emb expects (seq_len, device) and returns (cos, sin)
                position_embeddings = self._rotary_emb(seq_len, device=device)
                inputs["position_embeddings"] = position_embeddings
            except Exception:
                # Fallback: create dummy cos/sin tensors
                cos = torch.ones(1, seq_len, head_dim, device=device, dtype=dtype)
                sin = torch.zeros(1, seq_len, head_dim, device=device, dtype=dtype)
                inputs["position_embeddings"] = (cos, sin)
        else:
            # Fallback: create dummy cos/sin tensors
            cos = torch.ones(1, seq_len, head_dim, device=device, dtype=dtype)
            sin = torch.zeros(1, seq_len, head_dim, device=device, dtype=dtype)
            inputs["position_embeddings"] = (cos, sin)

        inputs["attention_mask"] = None
        return inputs

    def _apply_rotary_pos_emb(
        self, q: torch.Tensor, k: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Apply rotary position embeddings to query and key tensors.

        This implements the same logic as HuggingFace's apply_rotary_pos_emb.

        Args:
            q: Query tensor [batch, heads, seq_len, head_dim]
            k: Key tensor [batch, heads, seq_len, head_dim]
            cos: Cosine values [batch, seq_len, head_dim] or [1, seq_len, head_dim]
            sin: Sine values [batch, seq_len, head_dim] or [1, seq_len, head_dim]

        Returns:
            Tuple of (rotated_q, rotated_k)
        """
        # Add head dimension for broadcasting: [batch, 1, seq_len, head_dim]
        cos = cos.unsqueeze(1)
        sin = sin.unsqueeze(1)

        # Apply rotary embeddings
        # Split into rotary and passthrough dimensions
        rotary_dim = cos.shape[-1]
        q_rot, q_pass = q[..., :rotary_dim], q[..., rotary_dim:]
        k_rot, k_pass = k[..., :rotary_dim], k[..., rotary_dim:]

        # Apply rotation: q_embed = (q * cos) + (rotate_half(q) * sin)
        def rotate_half(x):
            """Rotates half the hidden dims of the input."""
            x1 = x[..., : x.shape[-1] // 2]
            x2 = x[..., x.shape[-1] // 2 :]
            return torch.cat((-x2, x1), dim=-1)

        q_embed = (q_rot * cos) + (rotate_half(q_rot) * sin)
        k_embed = (k_rot * cos) + (rotate_half(k_rot) * sin)

        # Concatenate with passthrough dimensions
        q_final = torch.cat([q_embed, q_pass], dim=-1) if q_pass.numel() > 0 else q_embed
        k_final = torch.cat([k_embed, k_pass], dim=-1) if k_pass.numel() > 0 else k_embed

        return q_final, k_final

    def _reconstruct_attention(
        self, q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, **kwargs
    ) -> tuple:
        """Attention reconstruction with rotary position embeddings and GQA support."""
        assert self.original_component is not None
        assert self.config is not None
        num_heads = self.config.n_heads
        num_kv_heads = getattr(self.config, "n_key_value_heads", None) or num_heads

        q, k, v, batch_size, seq_len, head_dim = self._reshape_qkv_to_heads(
            q, k, v, num_heads, num_kv_heads
        )

        # Apply rotary position embeddings if provided
        position_embeddings = kwargs.get("position_embeddings", None)
        if position_embeddings is not None and isinstance(position_embeddings, tuple):
            cos, sin = self._apply_position_embedding_hooks(position_embeddings)
            q, k = self._apply_rotary_pos_emb(q, k, cos, sin)

        # KV cache: extend K/V with cached positions.
        k, v = self._update_kv_cache(k, v, **kwargs)

        # GQA: expand K/V heads to match Q heads
        if num_kv_heads != num_heads:
            n_rep = num_heads // num_kv_heads
            k = k.repeat_interleave(n_rep, dim=1)
            v = v.repeat_interleave(n_rep, dim=1)

        kv_seq_len = k.shape[-2]  # Includes cached positions
        attn_scores = torch.matmul(q, k.transpose(-2, -1)) * (head_dim ** (-0.5))

        attention_mask = kwargs.get("attention_mask", None)
        attn_scores = self._apply_reconstruct_attention_mask(
            attn_scores=attn_scores,
            attention_mask=attention_mask,
            seq_len=kv_seq_len,
            q_seq_len=seq_len,
        )

        attn_scores = self.hook_attn_scores(attn_scores)
        attn_weights = self._softmax_dropout_pattern(attn_scores)

        attn_output = torch.matmul(attn_weights, v)
        attn_output = self._reshape_attn_output(
            attn_output, batch_size, seq_len, num_heads, head_dim
        )
        if (
            bool(getattr(self.config, "use_attn_result", False))
            and hasattr(self, "o")
            and self.o.original_component is not None
        ):
            attn_output = self.o.hook_in(attn_output)
            z_4d = attn_output.view(batch_size, seq_len, num_heads, head_dim)
            attn_output = self._compute_per_head_result(z_4d, num_heads, head_dim)
        else:
            attn_output = self._apply_output_projection(attn_output)
        return (attn_output, attn_weights)
