name: Release

on:
  release:
    types:
      - published

jobs:
  checks:
    name: Run checks workflow
    uses: TransformerLensOrg/TransformerLens/.github/workflows/checks.yml@main
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

  semver-parser:
    name: Parse the semantic version from the release
    runs-on: ubuntu-latest
    steps:
     - name: Parse semver string
       id: semver_parser 
       uses: booxmedialtd/ws-action-parse-semver@v1.4.7
       with:
         input_string: ${{ github.event.release.tag_name }}
    outputs:
      major: "${{ steps.semver_parser.outputs.major }}"
      minor: "${{ steps.semver_parser.outputs.minor }}"
      patch: "${{ steps.semver_parser.outputs.patch }}"
      semver: "${{ steps.semver_parser.outputs.fullversion }}"

  release-python:
    name: Release Python package to PyPi
    needs:
      - checks
      - semver-parser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          activate-environment: true
          enable-cache: true
      - name: Install dependencies
        run: |
          uv lock --check
          uv sync --locked
      - name: Set the version
        run: |
          sed -i "s/^version = \".*\"/version = \"${{needs.semver-parser.outputs.semver}}\"/" pyproject.toml
      - name: Build
        run: uv build
      - name: Publish
        run: |
          python -m pip install --upgrade twine
          twine upload --non-interactive -u __token__ -p "$POETRY_PYPI_TOKEN_PYPI" dist/*
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN_PYPI }}
